robot:
    interface: enp2s0
    joint_modules:
        motor_numbers: [0, 3, 2, 1, 5, 4, 6, 9, 8, 7, 11, 10]
        motor_constants: 0.025
        gear_ratios: 9.
        max_currents: 12.
        reverse_polarities: [
            true, true, true, false, false, false,
            true, true, true, false, false, false
        ]
        lower_joint_limits: [
            -1.2, -1.7, -3.4, -1.2, -1.7, -3.4,
            -1.2, -1.7, -3.4, -1.2, -1.7, -3.4
        ]
        upper_joint_limits: [
            1.2,  1.7, +3.4, +1.2, +1.7, +3.4,
            1.2,  1.7, +3.4, +1.2, +1.7, +3.4
        ]
        max_joint_velocities: 80.
        safety_damping: 0.5
    imu:
        rotate_vector: [1, 2, 3]
        orientation_vector: [-4, 3, -2, 1]
joint_calibrator:
    # Can be either POS, NEG, ALT or AUTO
    search_methods: [
      AUTO, AUTO, AUTO, AUTO, AUTO, AUTO,
      AUTO, AUTO, AUTO, AUTO, AUTO, AUTO
    ]
    position_offsets: [
        -0.54187584, -0.10114415, -0.03518456,
        -0.19963513,  0.2743632,  -0.27798976,
        -0.19362142,  0.24041801,  0.22988704,
         0.24115033, -0.10109035, -0.31003594
    ]
    calib_order: [1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0]
    calib_pos: [
        0.0,  1.2, -2.4,
        0.0,  1.2, -2.4,
        0.0, -1.2,  2.4,
        0.0, -1.2,  2.4
    ]
    Kp: 1.
    Kd: 0.05
    T: 1.
    dt: 0.002
